###get User Profile
GET  http://localhost:3000/user/profile
Authorization:Bearer {{$dotenv token}}


### edit User profile
Post http://localhost:3000/user/profile
Authorization:Bearer {{$dotenv token}}
Content-Type: application/json

{
    "first_name" : "" , 
    "last_name" : "" , 
    "skills" :["programing" , "nodejs" , "express.js"]
}